### ISSUE TITLE
[禁止登录]当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。

### ISSUE THREAD

**Issue by kfuudotcn** [howmanybots/onebot#44]
ticket也输入了，同一台电脑这个电脑QQ客户端可以正常登录

**Comment by kfuudotcn** [comment]
![image](https://user-images.githubusercontent.com/63281264/105368586-ab7fba80-5c3c-11eb-8a12-2cb2009f8bcb.png)

**Comment by sam01101** [comment]
这里是协议实现，不是给你这些错误回报的地方

**Comment by ieew** [comment]
@sam01101 这个问题与OneBot无关，并且mirai方面有解决方法，请去mirai查阅相关文档

**Comment by sam01101** [comment]
> @sam01101 这个问题与OneBot无关，并且mirai方面有解决方法，请去mirai查阅相关文档

回错人了（

**Comment by ieew** [comment]
这个问题与OneBot无关，并且mirai方面有解决方法，请去mirai查阅相关文档

**Comment by ieew** [comment]
> > @sam01101 这个问题与OneBot无关，并且mirai方面有解决方法，请去mirai查阅相关文档
> 
> 回错人了（

第一次使用tgbot，尴尬

**Comment by sam01101** [comment]
> 这个问题与OneBot无关，并且mirai方面有解决方法，请去mirai查阅相关文档

@kfuudotcn
